apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../../components/postgresql/overlays/common
  - secret.yaml
  - service_account.yaml

images:
  - name: IMAGE_NAME
    newName: postgres
    newTag: "14"

patches:
  - target:
      kind: Deployment
      name: COMPONENT_NAME
    patch: |-
      - op: add
        path: /spec/template/spec/serviceAccountName
        value: postgres-sa
      - op: add
        path: /spec/template/spec/containers/0/envFrom
        value:
        - secretRef:
            name: postgres
      - op: add
        path: /spec/template/spec/containers/0/volumeMounts
        value:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
      - op: add
        path: /spec/template/spec/volumes
        value:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgresql
